setGeneric("nobs", function(x,...) standardGeneric("nobs"))
setMethod("nobs", "data.frame", function(x) nrow(x))
setMethod("nobs", "zoo", function(x) nrow(x))
setMethod("nobs", "mts", function(x) nrow(x))
setMethod("nobs", "matrix", function(x) nrow(x))
